# Generated by Django 5.2.3 on 2025-07-01 23:19

import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comment_history',
            field=models.ManyToManyField(blank=True, related_name='commented_by_users', to='news.comment'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notification_preferences',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('World-News', 'World-News'), ('Local-News', 'Local-News'), ('Sport', 'Sport'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Scientific', 'Scientific'), ('Business', 'Business'), ('Politics', 'Politics')], max_length=81),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_read_history',
            field=models.ManyToManyField(blank=True, related_name='read_by_users', to='news.newspost'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='time_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
