# Generated by Django 5.2.3 on 2025-07-18 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='newspost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('ad_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text'), ('html', 'HTML Code')], max_length=10)),
                ('ad_space', models.CharField(choices=[('home-top', 'Home Page - Top Banner'), ('blogview-top', 'Blog View - Top'), ('blogview-bottom', 'Blog View - Bottom'), ('blogselect-sidebar', 'Blog Select - Sidebar'), ('blogselect-inline', 'Blog Select - Inline')], max_length=50)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('ad_text', models.TextField(blank=True, null=True)),
                ('html_code', models.TextField(blank=True, null=True)),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('World-News', 'World-News'), ('Local-News', 'Local-News'), ('Sport', 'Sport'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Scientific', 'Scientific'), ('Business', 'Business'), ('Politics', 'Politics')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.employeeaccount')),
                ('updated_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_updates', to='news.employeeaccount')),
            ],
        ),
        migrations.AddField(
            model_name='newspost',
            name='created_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.employeeaccount'),
        ),
        migrations.AddField(
            model_name='newspost',
            name='updated_by_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_updates', to='news.employeeaccount'),
        ),
        migrations.AddField(
            model_name='employeeaccount',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='news.manageraccount'),
        ),
    ]
