# Generated by Django 5.2.3 on 2025-06-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='category',
        ),
        migrations.AddField(
            model_name='newspost',
            name='main_category',
            field=models.CharField(choices=[('World News', 'World News'), ('Local News', 'Local News'), ('Sport', 'Sport'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Scientific', 'Scientific'), ('Business', 'Business'), ('Politics', 'Politics')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspost',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
