# Generated by Django 5.2.3 on 2025-07-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_customuser_comment_history_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='is_top_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newspost',
            name='top_news_priority',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Priority from 1 (highest) to 20 (lowest) for top news.', null=True, unique=True),
        ),
    ]
