# Generated by Django 5.2.3 on 2025-06-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newspost_main_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='main_category',
            field=models.CharField(choices=[('World-News', 'World-News'), ('Local-News', 'Local-News'), ('Sport', 'Sport'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Scientific', 'Scientific'), ('Business', 'Business'), ('Politics', 'Politics')], max_length=50),
        ),
    ]
