# Generated by Django 5.2.3 on 2025-07-09 15:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspost_is_top_news_newspost_top_news_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempNewsPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True, null=True)),
                ('header', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('source', models.CharField(max_length=255)),
                ('share_link', models.URLField(unique=True)),
                ('main_category', models.CharField(choices=[('World-News', 'World-News'), ('Local-News', 'Local-News'), ('Sport', 'Sport'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Scientific', 'Scientific'), ('Business', 'Business'), ('Politics', 'Politics')], max_length=50)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('paraphrased_content', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paraphrased', 'Paraphrased'), ('posted', 'Posted')], default='pending', max_length=20)),
            ],
        ),
    ]
